query allocationManagement($IDENTIFIER: IdentifierInput){
  allocationManagement(identifier: $IDENTIFIER){
    batches{
      id
      curriculumYear
      curriculumName
      batchYear
      batchSem
      courseLabs{
        courseId
        labId
      }
      courseAllocations{
        courseId
        facultyId
      }
      labAllocations{
        courseId
        facultyId
        isInCharge
      }
      courseIds
    }
    bestPreferences
    courses{
      id
      code
      name
      credit
      hours
      l
      t
      p
      isExtra
      isElective
      program
      curriculumYear
      batchYear
      sem
    }
    preferences{
      id
      facultyId
      courseId
      weigtage
      experience
      timestamp
      score
    }
    faculties{
      id
      user{
        id
        email
        firstName
        lastName
        username
        isStaff 
      }
      track
      designation
      minWorkload
      maxWorkload
      workload
    }
    
  }
}