query batch($BATCHID: ID!){
  batch(batchId:$BATCHID){
    curriculum{
      program
      year
    }
    year
    sem
    semesterExtraCourses{
      isElective
      name
      count
    }
    selectedExtraCourses{
      name
      courseType
    }
  }
}

query batchManagement {
  batchManagement {
    activeBatches{
      id
      program
      curriculumYear
      curriculumId
      sem
      year
      isComplete
    }
  }
}

query batches ($IDENTIFIER: IdentifierInput) {
  batches(identifier: $IDENTIFIER){
    curriculum{
      program
      year
    }
    
    semesterExtraCourses{
      isElective
      name
      count
    }
    selectedExtraCourses{
      id
      code
      name
      l
      t
      p
      credit
      hours
      courseType
    }
    extraCourseLeftToAssign
    year
    sem
  }
}