query programs {
  programs {
    id
    name
    duration
  }
}

query courses($IDENTIFIER: IdentfierInput) {
  courses(identifier: $IDENTIFIER) {
    id
    code
    name
    credit
    isExtra
    program
    curriculumYear
    batchYear
    sem
  }
}

query verifyNewCurriculum($PROGRAM: String!, $YEAR: Int!) {
  verifyNewCurriculum(program: $PROGRAM, year: $YEAR) {
    year
    sem
  }
}

query curriculums($PROGRAM: String, $YEAR: Int) {
  curriculums(program: "BCA", year: 2018) {
    program
    year
    duration
  }
}

query curriculumUpload ($PROGRAM:String!, $YEAR:Int!) {
  curriculumUpload(program:$PROGRAM, year:$YEAR){
    program
    year
    isPopulated
    uploadedOn
    data
  }
}

query curriculumUploads {
  curriculumUploads {
    id
    program
    year
    uploadedOn
    isPopulated
  }
}

query curriculumExtraCourses($EXTRAS: [String]!, $PROGRAM:String!, $CURRICULUMYEAR: Int!, $BATCHID: ID!){
  curriculumExtraCourses(extras:$EXTRAS ,program:$PROGRAM, curriculumYear:$CURRICULUMYEAR){
    extra
    courses{
      id
      code
      name
    }
  }
  batchSelectedExtraCourses(batchId:$BATCHID){
    id
    code
    name
    courseType
  }
}