query programs {
  programs{
    id
    name
    duration
  }
}

query verifyNewCurriculum($PROGRAM: String!, $YEAR: Int!){
  verifyNewCurriculum(program:$PROGRAM, year: $YEAR) {  
    year
    sem
  }
}

query curriculums($PROGRAM: String, $YEAR: Int){
  curriculums(program:"BCA", year:2018){
    program
    year
    duration
  }
}

query preferences ($IDENTIFIER: IdentfierInput, $COURSEID: ID){
  preferences(identifier: $IDENTIFIER, courseId:$COURSEID){
    id
    identifierYear
    identifierIsEvenSem
    faculty{
      user{
        firstName
        lastName
        username
      }
    }
    course{
      id
      code
      name
      credit
      l
      t
      p
      credit
      batch{
        year
        sem
        curriculum{
          program
          year
        }
      }
    }
    weigtage
    experience
    timestamp
  }
}