query programs {
  programs {
    id
    name
    duration
  }
}

query coursesForPreference {
  coursesForPreference{
    preferences{
      id
      identifierYear
      identifierIsEvenSem
      facultyId
      courseId
      weigtage
      experience
      timestamp
    }
    faculties{
      id
      track
      designation
      minWorkload
      maxWorkload
      workload
      user{
        id
        email
        firstName
        lastName        
      }
    }
    courses{
      id
      code
      name
      credit
      hours
      l
      t
      p
      isExtra
      isElective
      batchId
      sem
    }
    batches{
      id
      curriculumYear
      curriculumName
      batchYear
      batchSem
      courseLabs{
        courseId
        labId
      }
      courseIds
      courseAllocations{
        id
        courseId
        facultyId
      }
      labAllocations{
        id
        courseId
        facultyId
        isInCharge
      }      
    }
  }
}

query verifyNewCurriculum($PROGRAM: String!, $YEAR: Int!) {
  verifyNewCurriculum(program: $PROGRAM, year: $YEAR) {
    year
    sem
  }
}

query curriculums($PROGRAM: String, $YEAR: Int) {
  curriculums(program: "BCA", year: 2018) {
    program
    year
    duration
  }
}

query curriculumUpload ($PROGRAM:String!, $YEAR:Int!) {
  curriculumUpload(program:$PROGRAM, year:$YEAR){
    program
    year
    isPopulated
    uploadedOn
    data
  }
}

query curriculumUploads {
  curriculumUploads {
    id
    program
    year
    uploadedOn
    isPopulated
  }
}

query curriculumExtraCourses($EXTRAS: [String]!, $PROGRAM:String!, $CURRICULUMYEAR: Int!, $BATCHID: ID!){
  curriculumExtraCourses(extras:$EXTRAS ,program:$PROGRAM, curriculumYear:$CURRICULUMYEAR){
    extra
    courses{
      id
      code
      name
    }
  }
  batchSelectedExtraCourses(batchId:$BATCHID){
    id
    code
    name
    courseType
  }
}