query metadata {
    metadata {
        user {
            id
            email
            firstName
            lastName
            username
            isStaff
            isActive
        }
        faculty {
            id
            track
            designation
        }
        config {
            preferenceCount
            currentPreferenceSem {
                year
                isEvenSem
                startTimestamp
                endTimestamp
                isPaused
                areCoursesVerified
            }
        }
    }
}

