query me {
    me{
        id
        email
        firstName
        lastName
        username
        isStaff
    }
}

query faculty {
  faculty{
    user{
      id
      email
      firstName
      lastName
      username
      isStaff
    }
    track
    designation
  }
}

query faculties {
  faculties{
    user{
      id
      email
      firstName
      lastName
      username
      isStaff
      isActive
    }
    track
    designation
  }
}

query allocatedFaculties($IDENTIFIER: IdentifierInput!) {
  allocatedFaculties(identifier: $IDENTIFIER){
    id
    user{
      id
      email
      firstName
      lastName
    }
    track
    designation
  }
}

query workloads{
  workloads{
    track
    designation
    minHoursPerWeek
    maxHoursPerWeek
  }
}