# Generated by Django 3.2 on 2022-11-10 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20221110_1121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together={('course', 'faculty')},
        ),
        migrations.AlterUniqueTogether(
            name='laballocation',
            unique_together={('course', 'faculty')},
        ),
    ]
