# Generated by Django 3.2 on 2022-11-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20221110_1121'),
        ('allocation', '0002_auto_20221110_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course'),
        ),
    ]
