# Generated by Django 4.1.7 on 2023-03-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_sub'),
        ('allocation', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseallocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.faculty'),
        ),
        migrations.AlterField(
            model_name='laballocation',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.faculty'),
        ),
    ]
