# Generated by Django 3.2 on 2022-11-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('sem', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('credit', models.SmallIntegerField()),
                ('hours', models.SmallIntegerField()),
                ('l', models.SmallIntegerField()),
                ('t', models.SmallIntegerField()),
                ('p', models.SmallIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('credit', models.SmallIntegerField()),
                ('hours', models.SmallIntegerField()),
                ('l', models.SmallIntegerField()),
                ('t', models.SmallIntegerField()),
                ('p', models.SmallIntegerField()),
                ('is_elective', models.BooleanField(default=False)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.curriculumextras')),
                ('selected', models.ManyToManyField(to='course.Batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.program'),
        ),
        migrations.CreateModel(
            name='CourseLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='course.course')),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='course.course')),
            ],
        ),
    ]
