# Generated by Django 3.2 on 2022-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='courselab',
            unique_together={('course', 'lab')},
        ),
    ]
