# Generated by Django 3.2 on 2022-11-27 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='advisors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.curriculum'),
        ),
        migrations.AddField(
            model_name='batch',
            name='extras',
            field=models.ManyToManyField(to='course.CurriculumExtras'),
        ),
        migrations.AlterUniqueTogether(
            name='extracourse',
            unique_together={('code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumextras',
            unique_together={('curriculum', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('program', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='courselab',
            unique_together={('course', 'lab')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'name')},
        ),
    ]
