# Generated by Django 3.2 on 2022-11-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='advisors',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='extras',
        ),
        migrations.CreateModel(
            name='BatchCurriculumExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.batch')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.curriculumextras')),
            ],
            options={
                'unique_together': {('batch', 'extra')},
            },
        ),
    ]
