# Generated by Django 3.2 on 2022-11-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20221110_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courselab',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='course.course'),
        ),
        migrations.AlterField(
            model_name='courselab',
            name='lab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='course.course'),
        ),
        migrations.AlterUniqueTogether(
            name='courseidentifer',
            unique_together={('code', 'name')},
        ),
    ]
