# Generated by Django 3.2 on 2022-12-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20221130_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.curriculumextras'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.batch'),
        ),
        migrations.DeleteModel(
            name='ExtraCourse',
        ),
    ]
