# Generated by Django 4.1.7 on 2023-03-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20221218_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('data', models.JSONField()),
                ('is_populated', models.BooleanField(default=False)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.program')),
            ],
        ),
    ]
