# Generated by Django 4.1.7 on 2023-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_is_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumextras',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
