# Generated by Django 3.2 on 2022-11-08 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ASP', 'Assistant Professor'), ('ACP', 'Associate Professor'), ('PRF', 'Professor')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TH', 'Teaching'), ('SD', 'Standard'), ('RH', 'Research')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hours_per_week', models.SmallIntegerField()),
                ('max_hours_per_week', models.SmallIntegerField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.designation')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.track')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.SmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.courseidentifer')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.designation')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
