# Generated by Django 3.2 on 2022-11-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20221110_1121'),
        ('user', '0002_designation_faculty_facultyexperience_track_workload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(choices=[('ASP', 'Assistant Professor'), ('ACP', 'Associate Professor'), ('PRF', 'Professor')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(choices=[('TH', 'Teaching'), ('SD', 'Standard'), ('RH', 'Research')], max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='facultyexperience',
            unique_together={('course', 'faculty')},
        ),
        migrations.AlterUniqueTogether(
            name='workload',
            unique_together={('track', 'designation')},
        ),
    ]
