# Generated by Django 3.2 on 2022-11-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='max_hours_per_week',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workload',
            name='min_hours_per_week',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
