# Generated by Django 3.2 on 2022-11-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preference', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.faculty'),
        ),
        migrations.AddField(
            model_name='preference',
            name='preference_sem_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preference.identifier'),
        ),
        migrations.AlterUniqueTogether(
            name='identifier',
            unique_together={('year', 'is_even_sem')},
        ),
        migrations.AddField(
            model_name='config',
            name='current_preference_sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='preference.identifier'),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('faculty', 'course')},
        ),
    ]
