# Generated by Django 4.1.7 on 2023-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='are_courses_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identifier',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identifier',
            name='is_paused',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='identifier',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
