# Generated by Django 3.2 on 2022-11-18 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_auto_20221110_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
