# Generated by Django 4.1.7 on 2023-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0003_identifier_are_courses_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='is_hod_approved',
            field=models.BooleanField(default=False),
        ),
    ]
